#! /bin/sh

bspc config border_width        2
bspc config window_gap         12
bspc config focused_border_color "#1166FF"

i=1
for monitor in $(bspc query -M); do
    bspc monitor $monitor -n "$i" -d $i/{i,ii,iii,iv,v,vi,vii,viii,ix,x}
    let i++
    bspc monitor -d
done
NMON=$i
unset i

if [ -e "$BSPWM_TREE" ] ; then
  bspc restore -T "$BSPWM_TREE" -H "$BSPWM_HISTORY" -S "$BSPWM_STACK"
  rm "$BSPWM_TREE" "$BSPWM_HISTORY" "$BSPWM_STACK"
fi

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true

bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
