# -*- mode: sh -*-

# fix for tramp
if [[ "$TERM" == "dumb" ]]; then source ~/conf.d/bashrc; return; fi

if type brew &>/dev/null
then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

  autoload -Uz compinit
  compinit
fi

source ~/conf.d/zsh/zprezto/init.zsh
source ~/conf.d/zsh/zpreztorc
source ~/conf.d/bashrc

zmodload zsh/complist
setopt CLOBBER
unsetopt share_history
unsetopt auto_cd

setopt rmstarsilent
alias rsync='noglob rsync'
alias scp='noglob scp'

# For screen
if [ -n "$STY" ]; then
    precmd () { echo -ne "\ek$(basename "$(readlink -e .)")\e\\" }
    preexec () { echo -ne "\ek${1}\e\\" }
fi

bindkey -e
bindkey -M emacs "$key_info[Control]u" backward-kill-line
bindkey -M menuselect '^M' .accept-line

export WORDCHARS=''
export SHELL=`which zsh`

# huge history
HISTSIZE=10000000
SAVEHIST=10000000

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

if [[ -n $(hasbin thefuck) ]]; then
    eval $(thefuck --alias)
fi
